GET http://localhost:8080/A/sessions HTTP/1.1

###

POST http://localhost:8080/A/sessions HTTP/1.1
content-type: application/json

{
	"owner": {
		"name": "Aslak",
		"peerid": "x"
	}
}

### 

GET http://localhost:8080/A/sessions/0 HTTP/1.1

###

PATCH http://localhost:8080/A/sessions/0 HTTP/1.1

{
	"participants": [
		{
			"name": "Aslak 4",
			"peerid": "x"
		}
	]
}
